$(document).ready(function(){
    $('#bmenos').click(function(Event){
    Event.preventDefault();
    $('#menos').hide('slow');
    $('#bmas').show('1000');
});
$('#bmas').click(function(Event){
    Event.preventDefault();
    $('#menos').show('1000');
    $(this).hide();
});
$('#bmenos1').click(function(Event){
Event.preventDefault();
$('#menos1').hide('slow');
$('#bmas1').show('1000');
});
$('#bmas1').click(function(Event){
Event.preventDefault();
$('#menos1').show('1000');
$(this).hide();
});
$('#bmenos2').click(function(Event){
Event.preventDefault();
$('#menos2').hide('slow');
$('#bmas2').show('1000');
});
$('#bmas2').click(function(Event){
Event.preventDefault();
$('#menos2').show('1000');
$(this).hide();
});
$('#bmenos3').click(function(Event){
Event.preventDefault();
$('#menos3').hide('slow');
$('#bmas3').show('1000');
});
$('#bmas3').click(function(Event){
Event.preventDefault();
$('#menos3').show('1000');
$(this).hide();
});
$('#bmenos4').click(function(Event){
Event.preventDefault();
$('#menos4').hide('slow');
$('#bmas4').show('1000');
});
$('#bmas4').click(function(Event){
Event.preventDefault();
$('#menos4').show('1000');
$(this).hide();
});
$('#bmenos5').click(function(Event){
Event.preventDefault();
$('#menos5').hide('slow');
$('#bmas5').show('1000');
});
$('#bmas5').click(function(Event){
Event.preventDefault();
$('#menos5').show('1000');
$(this).hide();
});
});
